version: 2.1
orbs:
  cloudfoundry: circleci/cloudfoundry@0.1.73
workflows:
  build-deploy-prod:
    jobs:
      - cloudfoundry/push:
          appname: uxg
          org: DOF-DSS
          endpoint: https://api.london.cloud.service.gov.uk
          space: production
          context: govuk-paas-production
          manifest: manifest.yml
